### ISSUE TITLE
The Homepage of your crate on crates.io is broken

### ISSUE THREAD

**Issue by danielthegray** [plopgrizzly/asi_opengl#1]
If you check at https://crates.io/crates/asi_opengl, the homepage link points to http://plopgrizzly.com/asi_opengl which returns 404.

I found your Github pages site at https://github.com/plopgrizzly/plopgrizzly.github.io but there doesn't seem to be any folder or old link which contained that file (otherwise I would have tried to fix it and send a pull request). Just thought I'd let you know.

**Comment by AldaronLau** [comment]
Thanks for pointing this out for me.  I just made a commit, publishing the page.  It no longer returns 404.

**Comment by danielthegray** [comment]
The `adi_gpu_opengl` (https://crates.io/crates/adi_gpu_opengl) crate's homepage link points to:
 http://plopgrizzly.com/adi_gpu_opengl
which is also 404-ing.

**Comment by AldaronLau** [comment]
Thanks, again!  Should be fixed, now.
